fieldLayouts:
  ea4a2d84-4ee4-4e07-b611-df7eafaf14cc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 5fdac679-4921-4fb2-939b-88793a3666d6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2b6ba2fc-c9f5-4598-a893-7dd3931f97b0 # Dates
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9d3e9bd3-6011-4ffe-b601-dc5f166eb59a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39f6a1f9-5e31-41bb-ad6b-30dd22aefc80
        userCondition: null
handle: event
hasTitleField: true
name: Event
section: fa9f5968-32b5-4b05-b093-6bc4ef63ed9a # Events
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
