fieldLayouts:
  982d1856-ab0d-4255-99af-3b9b2cf21e73:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 53c06e16-eeec-47bd-93f6-bbedc9108d74
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: ac7d28ea-81c0-4cf4-8e68-d37c81cb05c9
        userCondition: null
fs: competitors
handle: competitors
name: Competitors
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
