columnSuffix: zsrmwbmz
contentColumnType: integer(10)
fieldGroup: 31006d4c-2f40-498c-9a4c-69cff4fd4279 # Common
handle: score
instructions: 'The lower the better.'
name: Score
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
