dateModified: 1688718011
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - filename
        - asc
      disabled: false
      key: 'volume:1b95b48c-6fd9-401d-bdc6-cd251a02d62b' # Competitors
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      defaultSort:
        - filename
        - asc
      disabled: false
      key: 'volume:9f09fed0-269d-48bf-9b3a-4a0a3abc44e0' # Flags
      tableAttributes:
        - filename
        - size
        - dateModified
        - uploader
        - link
      type: native
    -
      key: 'folder:52e0e4e6-a037-42c1-80dc-f7e300176065'
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - 'field:6ba159b8-0e40-4ff9-b825-ceed90bdab7f'
        - asc
      disabled: false
      key: 'section:fa9f5968-32b5-4b05-b093-6bc4ef63ed9a' # Events
      tableAttributes:
        - 'field:6ba159b8-0e40-4ff9-b825-ceed90bdab7f'
        - 'field:846a33bd-87d8-4ec4-909f-32bd6399c92f'
        - 'field:8278aaa3-21b9-457a-b25e-f0d5a43fdc35'
      type: native
    -
      defaultSort:
        - title
        - asc
      disabled: false
      key: 'section:c196afcb-c41e-4d19-8ff6-e95d277f98af'
      tableAttributes:
        - 'field:6b6005ce-5d9a-4135-a8d1-48ae9c595f28'
      type: native
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - link
      type: native
email:
  fromEmail: info@domain.com
  fromName: 'Craft Coding Challenge'
  replyToEmail: null
  template: ''
  transportSettings:
    command: '/usr/sbin/sendmail -bs'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  competitors:
    hasUrls: true
    name: Competitors
    settings:
      path: '@webroot/assets/competitors'
    type: craft\fs\Local
    url: '@web/assets/competitors'
  flags:
    hasUrls: true
    name: Flags
    settings:
      path: '@webroot/assets/flags'
    type: craft\fs\Local
    url: '@web/assets/flags'
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0d89c679-f6f5-42ae-8341-4bea917c6af7: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    1b95b48c-6fd9-401d-bdc6-cd251a02d62b: Competitors # Competitors
    2b6ba2fc-c9f5-4598-a893-7dd3931f97b0: Dates # Dates
    9f09fed0-269d-48bf-9b3a-4a0a3abc44e0: Flags # Flags
    0779f354-f5d2-4f82-9a36-28a252f70ce4: 'Public Schema' # Public Schema
    31006d4c-2f40-498c-9a4c-69cff4fd4279: Common # Common
    c7c2807b-84cc-4e1f-9279-af044bc0b472: 'Public Schema' # Public Schema
    d617503a-3829-4390-9c8f-7fb6612a702c: Event # Event
    f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    fa9f5968-32b5-4b05-b093-6bc4ef63ed9a: Events # Events
plugins:
  elements-panel:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
